name: Slack Notification
'on':
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SE_TOOL_REQUESTS_WEBHOOK }}
          SLACK_CHANNEL: se-tool-requests
          SLACK_COLOR: good
          SLACK_ICON: https://a.storyblok.com/f/92909/x/0489b50911/favicon.ico
          SLACK_MESSAGE: |
            ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.url }}
          SLACK_TITLE: 'Octolint PR Created'
          SLACK_USERNAME: 'Slack Notification Workflow'
          SLACK_FOOTER: ''
          MSG_MINIMAL: true
